# Site settings
title: Azerus | Developer's Blog
info-email: hey@himanshupatel.net
support-email: support@himanshupatel.net
copyright: "All Rights Reserved | The Designable LLC - Russia | France | India"
description: > # this means to ignore newlines until "baseurl:"
 Developer's of Azerus Blogging Platform. Developed by The Designable LLC.
 Please note this blog is for any updates related to Azerus public release.
 Public Beta is under construction. For any queries send a mail to developers@thedesignable.com.
 Make sure you add "Azerus" in your subject line. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://thedesignable.github.io" # the base hostname & protocol for your site
twitter_username: thedesignable
github_username:  thedesignable


# Build settings
highlighter: pygments
markdown: kramdown
